### ISSUE TITLE
[扩展需求] 是否会有nuget包提供?

### ISSUE THREAD

**Issue by LorisYounger** [Coloryr/Live2DCSharpSDK#1]
如题, 是否会提供nuget包?

顺便作者加油! 我特意升级了项目到.net8就是为了能用你的包

**Comment by Coloryr** [comment]
我不知道怎么发布nuget包

**Comment by Coloryr** [comment]
等我更新了最新版打包个试试

**Comment by Coloryr** [comment]
https://www.nuget.org/packages/Live2DCSharpSDK
