### ISSUE TITLE
[集成帮助] 关于在WPF上的使用问题

### ISSUE THREAD

**Issue by LorisYounger** [Coloryr/Live2DCSharpSDK#2]
我正在尝试使用该项目在WPF上, 因为案例只有OpenTK, 我尝试使用 [OpenTK.GLWpfControl](https://github.com/opentk/GLWpfControl) 迁移到 WPF上

不知道为啥没法正常运行, 当运行时, 并不会显示动画,而是显示 
`OpenGL Content. Call Start() on the control to begin rendering`

代码地址 [Live2DCSharpSDK.WPF](https://github.com/LorisYounger/Live2DCSharpSDK/tree/master/Live2DCSharpSDK.WPF)

如果可以的话能否帮忙看看原因? 或者官方是否提供其他使用该项目到WPF的例子?

感激不尽

**Comment by Coloryr** [comment]
你按照官方给的实例写试试，估计Start要在控件初始化阶段

**Comment by LorisYounger** [comment]
官方给的实例 `Live2DCSharpSDK.OpenTK` 里面没有Start相关操作,好像直接就启动了
我也使用了 `GLControl.Start(settings);` 来启动项目, 

https://github.com/LorisYounger/Live2DCSharpSDK/blob/9831af3b9cec38b52665764e32fb942dd52dd4db/Live2DCSharpSDK.WPF/MainWindow.xaml.cs#L44-L59

也没有成功

**Comment by Coloryr** [comment]
我指的是https://github.com/opentk/GLWpfControl?tab=readme-ov-file#getting-started

**Comment by LorisYounger** [comment]
成了! 现在能正常运行了
![image](https://github.com/Coloryr/Live2DCSharpSDK/assets/34806646/668c4482-9f78-463a-bf39-9934653e7b10)

话说需要PR添加这个WPF案例到Live2DCSharpSDK吗?

**Comment by LorisYounger** [comment]
话说这个标准模型缺个眼睛, 我在 `Live2DCSharpSDK.OpenTK` 里运行的时候也会缺个眼睛
上一个版本好像没有这个问题

**Comment by Coloryr** [comment]
这个我不记得怎么解决了，要改渲染设置

**Comment by Coloryr** [comment]
这个是框架问题，好像有哪里写错了，等我找时间看看

**Comment by LorisYounger** [comment]
![image](https://github.com/Coloryr/Live2DCSharpSDK/assets/34806646/57819a9c-454e-4ca3-b691-7af34431b6ae)
我这边使用旧版本sdk就是好的, 有眼睛的, 新版本就没有了
大概是 2024/2/22日之前的版本

对比了下时间,应该是这个版本
https://github.com/Coloryr/Live2DCSharpSDK/commit/e52dc65e7e7a5bf8a39a3578c44e1bd112f9cf61
当时下载的代码如下:
[Live2DCSharpSDK-master.zip](https://github.com/Coloryr/Live2DCSharpSDK/files/14882924/Live2DCSharpSDK-master.zip)
