### ISSUE TITLE
[新人求助] OpenTK 和 Wpf 的示例没法成功运行

### ISSUE THREAD

**Issue by yueyinqiu** [Coloryr/Live2DCSharpSDK#5]
大佬们好，我是直接克隆了这个仓库运行，只修改了模型的位置。（ `Live2DCubismCore.dll` 直接放在了 `bin\Debug\net8.0` 目录下。）

---

这是 `Live2DCSharpSDK.WPF` 的情况，界面一直是黑色的：

![QQ_1720011923276](https://github.com/Coloryr/Live2DCSharpSDK/assets/18749772/85825aec-1e7c-4ebb-81bc-f10ef540fd9d)

---

这是 `Live2DCSharpSDK.OpenTK` ：

![QQ_1720012379805](https://github.com/Coloryr/Live2DCSharpSDK/assets/18749772/5cd9e719-22ec-4aac-a65c-b31d71bddc55)

其中 `code` 是 `InvalidOperation` 。（注释掉这个 `throw` 之后看起来倒是可以正常运行的。）

---

`Live2DCSharpSDK.Avalonia` 好像没什么问题。但是它好像也没有，比如随着鼠标点击产生某些动作之类的。想问一问有没有这种可以触发某些动作的示例或者教程呀？想做一个桌面宠物之类的。

**Comment by Coloryr** [comment]
https://github.com/Coloryr/ColorMC/blob/master/src/ColorMC.Gui/UI/Controls/Main/Live2dRender.cs
那你看看这个

**Comment by Coloryr** [comment]
![image](https://github.com/Coloryr/Live2DCSharpSDK/assets/26276037/bf930f75-73b0-4d3d-bd7b-3976e1802273)
我这边WPF是正常的，看看你的显卡驱动有了没

**Comment by Coloryr** [comment]
![image](https://github.com/Coloryr/Live2DCSharpSDK/assets/26276037/a8128d36-8659-4dd3-acf9-50ad496bab24)
OpenTK也是

**Comment by yueyinqiu** [comment]
谢谢大佬，我再看看（（

**Comment by yueyinqiu** [comment]
emmm我试了一下，在自己电脑上编译之后在其他电脑上跑是没有问题的……

我检查了显卡驱动，它已经是最新版了，会不会是这个不支持笔记本的核显？还有什么其他可能的原因吗？

**Comment by Coloryr** [comment]
我不知道
